# On lie uniquement l'URL complète. Spring Boot va extraire tout seul le user et le password cachés dedans !
spring.datasource.url=${DATABASE_URL}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
server.port=${PORT:8080}